Changes to README.md
masaguaro/machine_learning_notes pull request #1
Opened 2018-09-12 14:37 UTC by masaguaro

Hi, these are some changes I made to README.db after discussing with Mani.. Feel free to make any comment or suggestion to improve them.

2018-09-12 15:38 UTC, neomatrix369 commented
@masaguaro good work, I'll post my comments, I suggest you install Grammarly plugin (https://www.grammarly.com) on your browser it will help correct any future mistakes - I understand English isn't our first language

2018-09-12 15:41 UTC, neomatrix369 commented on README.md
> +work on kaggle ML project.
What is this a title or just a note?

2018-09-12 15:41 UTC, neomatrix369 commented on README.md
> +https://www.kaggle.com/c/house-prices-advanced-regression-techniques.
Dot at the end isn't required

2018-09-12 15:41 UTC, neomatrix369 commented on README.md
> +This project is the result of the joined effort of a study group of enthusiastic people from different professional background. Anyone is welcome to join and to contribute with the discussion.
joined => joint effort

2018-09-12 15:41 UTC, neomatrix369 commented on README.md
> +This project is the result of the joined effort of a study group of enthusiastic people from different professional background. Anyone is welcome to join and to contribute with the discussion.
discussion ==> discussions

2018-09-12 15:41 UTC, neomatrix369 commented on README.md
> +The best way to join to the project is by assisting to on our regular session.  Also, feel free to fork and check what we have done in this project. We are very happy to receive any comment and sugge
to on our regular session ==> during our regular sessions

2018-09-12 15:41 UTC, neomatrix369 commented on README.md
> +* [Load data and displaying info](#load-data)
Indentation to the right

2018-09-12 15:41 UTC, neomatrix369 commented on README.md
> +This notebook contains a reference for some techniques to tackle the problem to detect and remove outliers sample from the data set.
all throughout the text, `dataset` is one word, and not `data set` try to remove the spaces where required

2018-09-12 15:42 UTC, neomatrix369 requested changes
LGTM - except a few comments left on the page

2018-09-12 15:42 UTC, neomatrix369 commented
Try to use grammarly to see if it helps improve the sentences otherwise its fine the way it is

2018-09-12 16:26 UTC, masaguaro commented on README.md
> +The best way to join to the project is by assisting to on our regular session.  Also, feel free to fork and check what we have done in this project. We are very happy to receive any comment and sugge
Does it sound better? 'The best way to join the project is by assisting during our regular sessions.'

2018-09-13 15:07 UTC, neomatrix369 commented
Merging nw, as agreed, any other pending stuff we do via a new PR

2018-09-13 15:07 UTC, merged